# Generated by Django 4.0.4 on 2022-05-04 09:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todo',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
